name: Push Docker Image

on:
  release:
    types:
      - published

jobs:
  push-docker-image:
    uses: Juansecu/Red5-Docker/.github/workflows/push-docker-image.yml@314b0deb22f6e92c7538b7d246fa68e806856363
    with:
      version: ${{ github.event.release.tag_name }}
